import { type TDeteccao, type TDeteccaoStatus } from "~/constants/deteccao";

export const marcas = [];

export const deteccoesGroupedByStatus = {
  concluido: [
    {
      id: 1,
      periodo: {
        id: 4,
        start: {
          at: "2023-03-03T00:00:00Z",
          thumbnail_url: "https://picsum.photos/600/400",
        },
        end: {
          at: "2023-04-16T00:00:00Z",
          thumbnail_url: "https://picsum.photos/600/400",
        },
      },
      location: [-43.172, -22.906],
      created_at: "18 de mai",
      updated_at: "23 de mai",
      thumbnail_url: "https://picsum.photos/600/400",
      attraction: {
        id: 1,
        slug: "red-hot-chili-peppers",
        name: "Red Hot Chili Peppers",
      },
      status: "concluido",
    },
    {
      id: 2,
      periodo_start_thumbnail_url: "https://picsum.photos/600/400",
      periodo_end_thumbnail_url: "https://picsum.photos/600/400",
      periodo_start_at: "3 de mar",
      periodo_end_at: "16 de abr",
      created_at: "18 de mai",
      updated_at: "23 de mai",
      thumbnail_url: "https://picsum.photos/600/400",
      status: "concluido",
    },
    {
      id: 3,
      periodo_start_thumbnail_url: "https://picsum.photos/600/400",
      periodo_end_thumbnail_url: "https://picsum.photos/600/400",
      periodo_start_at: "3 de mar",
      periodo_end_at: "16 de abr",
      created_at: "18 de mai",
      updated_at: "23 de mai",
      thumbnail_url: "https://picsum.photos/600/400",
      status: "concluido",
    },
  ],
  processando: [
    {
      id: 9,
      periodo_start_thumbnail_url: "https://picsum.photos/600/400",
      periodo_end_thumbnail_url: "https://picsum.photos/600/400",
      periodo_start_at: "3 de mar",
      periodo_end_at: "16 de abr",
      created_at: "18 de mai",
      updated_at: "23 de mai",
      thumbnail_url: "https://picsum.photos/600/400",
      status: "processando",
    },
    {
      id: 10,
      periodo_start_thumbnail_url: "https://picsum.photos/600/400",
      periodo_end_thumbnail_url: "https://picsum.photos/600/400",
      periodo_start_at: "3 de mar",
      periodo_end_at: "16 de abr",
      created_at: "18 de mai",
      updated_at: "23 de mai",
      thumbnail_url: "https://picsum.photos/600/400",
      status: "processando",
    },
    {
      id: 11,
      periodo_start_thumbnail_url: "https://picsum.photos/600/400",
      periodo_end_thumbnail_url: "https://picsum.photos/600/400",
      periodo_start_at: "3 de mar",
      periodo_end_at: "16 de abr",
      created_at: "18 de mai",
      updated_at: "23 de mai",
      thumbnail_url: "https://picsum.photos/600/400",
      status: "processando",
    },
    {
      id: 12,
      periodo_start_thumbnail_url: "https://picsum.photos/600/400",
      periodo_end_thumbnail_url: "https://picsum.photos/600/400",
      periodo_start_at: "3 de mar",
      periodo_end_at: "16 de abr",
      created_at: "18 de mai",
      updated_at: "23 de mai",
      thumbnail_url: "https://picsum.photos/600/400",
      status: "processando",
    },
    {
      id: 13,
      periodo_start_thumbnail_url: "https://picsum.photos/600/400",
      periodo_end_thumbnail_url: "https://picsum.photos/600/400",
      periodo_start_at: "3 de mar",
      periodo_end_at: "16 de abr",
      created_at: "18 de mai",
      updated_at: "23 de mai",
      thumbnail_url: "https://picsum.photos/600/400",
      status: "processando",
    },
    {
      id: 14,
      periodo_start_thumbnail_url: "https://picsum.photos/600/400",
      periodo_end_thumbnail_url: "https://picsum.photos/600/400",
      periodo_start_at: "3 de mar",
      periodo_end_at: "16 de abr",
      created_at: "18 de mai",
      updated_at: "23 de mai",
      thumbnail_url: "https://picsum.photos/600/400",
      status: "processando",
    },
    {
      id: 15,
      periodo_start_thumbnail_url: "https://picsum.photos/600/400",
      periodo_end_thumbnail_url: "https://picsum.photos/600/400",
      periodo_start_at: "3 de mar",
      periodo_end_at: "16 de abr",
      created_at: "18 de mai",
      updated_at: "23 de mai",
      thumbnail_url: "https://picsum.photos/600/400",
      status: "processando",
    },
    {
      id: 16,
      periodo_start_thumbnail_url: "https://picsum.photos/600/400",
      periodo_end_thumbnail_url: "https://picsum.photos/600/400",
      periodo_start_at: "3 de mar",
      periodo_end_at: "16 de abr",
      created_at: "18 de mai",
      updated_at: "23 de mai",
      thumbnail_url: "https://picsum.photos/600/400",
      status: "processando",
    },
    {
      id: 17,
      periodo_start_thumbnail_url: "https://picsum.photos/600/400",
      periodo_end_thumbnail_url: "https://picsum.photos/600/400",
      periodo_start_at: "3 de mar",
      periodo_end_at: "16 de abr",
      created_at: "18 de mai",
      updated_at: "23 de mai",
      thumbnail_url: "https://picsum.photos/600/400",
      status: "processando",
    },
  ],
  pendente: [
    {
      id: 4,
      periodo_start_thumbnail_url: "https://picsum.photos/600/400",
      periodo_end_thumbnail_url: "https://picsum.photos/600/400",
      periodo_start_at: "3 de mar",
      periodo_end_at: "16 de abr",
      created_at: "18 de mai",
      updated_at: "23 de mai",
      thumbnail_url: "https://picsum.photos/600/400",
      status: "pendente",
    },
    {
      id: 5,
      periodo_start_thumbnail_url: "https://picsum.photos/600/400",
      periodo_end_thumbnail_url: "https://picsum.photos/600/400",
      periodo_start_at: "3 de mar",
      periodo_end_at: "16 de abr",
      created_at: "18 de mai",
      updated_at: "23 de mai",
      thumbnail_url: "https://picsum.photos/600/400",
      status: "pendente",
    },
    {
      id: 6,
      periodo_start_thumbnail_url: "https://picsum.photos/600/400",
      periodo_end_thumbnail_url: "https://picsum.photos/600/400",
      periodo_start_at: "3 de mar",
      periodo_end_at: "16 de abr",
      created_at: "18 de mai",
      updated_at: "23 de mai",
      thumbnail_url: "https://picsum.photos/600/400",
      status: "pendente",
    },
    {
      id: 7,
      periodo_start_thumbnail_url: "https://picsum.photos/600/400",
      periodo_end_thumbnail_url: "https://picsum.photos/600/400",
      periodo_start_at: "3 de mar",
      periodo_end_at: "16 de abr",
      created_at: "18 de mai",
      updated_at: "23 de mai",
      thumbnail_url: "https://picsum.photos/600/400",
      status: "pendente",
    },
    {
      id: 8,
      periodo_start_thumbnail_url: "https://picsum.photos/600/400",
      periodo_end_thumbnail_url: "https://picsum.photos/600/400",
      periodo_start_at: "3 de mar",
      periodo_end_at: "16 de abr",
      created_at: "18 de mai",
      updated_at: "23 de mai",
      thumbnail_url: "https://picsum.photos/600/400",
      status: "pendente",
    },
  ],
} as const satisfies Record<TDeteccaoStatus, TDeteccao[]>;

export const flattenedDeteccoes = Object.values(
  deteccoesGroupedByStatus,
).flat();

export const deteccoesCount = Object.values(flattenedDeteccoes).length;
