// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package services

type Proposta struct {
	ID       int64  `json:"id"`
	Status   string `json:"status"`
	Name     string `json:"name"`
	Assignee string `json:"assignee"`
}
