// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: services.sql

package services

import (
	"context"
)

const listPropostas = `-- name: ListPropostas :many
SELECT
    id,
    status,
    name,
    assignee
FROM propostas
ORDER BY status
`

func (q *Queries) ListPropostas(ctx context.Context) ([]Proposta, error) {
	rows, err := q.db.QueryContext(ctx, listPropostas)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Proposta
	for rows.Next() {
		var i Proposta
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.Name,
			&i.Assignee,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
