// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package queries

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type PropostaStatus string

const (
	PropostaStatusBacklog PropostaStatus = "backlog"
)

func (e *PropostaStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PropostaStatus(s)
	case string:
		*e = PropostaStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PropostaStatus: %T", src)
	}
	return nil
}

type NullPropostaStatus struct {
	PropostaStatus PropostaStatus
	Valid          bool // Valid is true if PropostaStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPropostaStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PropostaStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PropostaStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPropostaStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PropostaStatus), nil
}

type Proposta struct {
	ID         int32
	Status     PropostaStatus
	Name       string
	AssigneeID pgtype.Int4
}

type PropostaAttachment struct {
	ID         int32
	PropostaID int32
}

type User struct {
	ID       int32
	Email    string
	Password string
}
